import type { Metadata } from 'next'
//import { Inter } from 'next/font/google'
import './globals.css'
import "./components/styles/buttons.css";
import "./components/styles/hero-section.css"
import HomePage from './page';
import Head from "next/head";
import Heade from "./components/head";


//import { NavBar } from "./components/NavBar";
/* import { HeroSection } from "./components/HeroSection";
import { IconWrapper } from "./components/Icon-Wrapper"; */
//import HomePage from './page';
//import { Reviews } from "./components/reviews";

//const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
    <Heade/>
        {/* <HeroSection className="" />
        <IconWrapper /> */}
        {/* <Reviews property1="" className="" /> */}


        {children}</body>
    </html>
  )
}
